/* eslint-disable */
export const shortcuts = [
    {
        id         : 'a1ae91d3-e2cb-459b-9be9-a184694f548b',
        label      : 'Yeni Eklenenler',
        description: 'Yeni eklenen kitaplar',
        icon       : 'heroicons_outline:clipboard-document-list',
        link       : '/library/new-arrivals',
        useRouter  : true,
    },
    {
        id         : '989ce876-c177-4d71-a749-1953c477f825',
        label      : 'Rehber',
        description: 'Kütüphane rehberi',
        icon       : 'heroicons_outline:book-open',
        link       : '/library/guide',
        useRouter  : true,
    },
    {
        id         : '2496f42e-2f25-4e34-83d5-3ff9568fd984',
        label      : 'Yardım Merkezi',
        description: 'SSS ve rehberler',
        icon       : 'heroicons_outline:information-circle',
        link       : '/library/help-center',
        useRouter  : true,
    },
    {
        id         : '3c48e75e-2ae7-4b73-938a-12dc655be28b',
        label      : 'Kitap Listesi',
        description: 'Kütüphanedeki kitaplar',
        icon       : 'heroicons_outline:chart-pie',
        link       : '/library/book-list',
        useRouter  : true,
    },
    {
        id         : '2daac375-a2f7-4393-b4d7-ce6061628b66',
        label      : 'Mesajlar',
        description: 'Yeni mesajlarınız var',
        icon       : 'heroicons_outline:envelope',
        link       : '/library/messages',
        useRouter  : true,
    },
    {
        id         : '56a0a561-17e7-40b3-bd75-0b6cef230b7e',
        label      : 'Görevler',
        description: 'Tamamlanmamış görevler',
        icon       : 'heroicons_outline:check-circle',
        link       : '/library/tasks',
        useRouter  : true,
    },
    {
        id         : 'f5daf93e-b6f3-4199-8a0c-b951e92a6cb8',
        label      : 'Üyeler',
        description: 'Tüm üyeleri listele',
        icon       : 'heroicons_outline:user-group',
        link       : '/library/members',
        useRouter  : true,
    },
    {
        id         : '0a240ab8-e19d-4503-bf68-20013030d526',
        label      : 'Uygulamayı Yenile',
        description: 'Uygulamayı yenile',
        icon       : 'heroicons_outline:arrow-path',
        link       : '/library/home',
        useRouter  : false,
    },
];
